frontend:
  - changed-files:
      - any-glob-to-any-file: ['**/*.{js,jsx,ts,tsx,css,scss}']

docs:
  - changed-files:
      - any-glob-to-any-file: ['docs/**', '**/*.md']

design:
  - changed-files:
      - any-glob-to-any-file: ['ui/**', 'design/**']
